name: todo_list
description: 'A new Flutter project. Created by Slidy'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build_context: ^2.0.0
  intl: ^0.16.1
  google_fonts: ^1.1.0
  # get: ^2.0.9-dev
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
  watch: flutter pub run build_runner watch --delete-conflicting-outputs